# -*- coding: utf-8 -*-
"""Atividade_2_ESll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1cD-Gu6IS_Y167uG077u5kcnhpaHQAZ
"""

!pip install -q transformers accelerate sentencepiece gitpython

!git clone https://github.com/microsoft/JARVIS.git || true

import os

files_of_interest = ["README.md", "CONTRIBUTING.md", "SECURITY.md", "SUPPORT.md"]

texts = []

for file in files_of_interest:
    path = os.path.join("JARVIS", file)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            texts.append(f"\n### {file}\n" + f.read())

print("Arquivos carregados:", len(texts))
corpus = "\n".join(texts)

from transformers import pipeline

pipe = pipeline("text2text-generation", model="google/flan-t5-large", device_map="auto")

prompt_release = f"""
You are analyzing the documentation of an open-source software project
from a Software Engineering and governance perspective.

Task:
Classify the project's RELEASE STRATEGY based ONLY on explicit or implicit
evidence found in the provided documentation.

Guidelines:
- Do NOT infer release strategy from commit frequency.
- Do NOT assume commercial product practices.
- Research-oriented projects often follow Ad-hoc or Research-based releases.
- If no clear release policy, schedule, or cadence is documented, reflect that.

Choose ONLY ONE of the following options as your answer:
- Rapid Releases
- Release Train
- LTS + Current
- Ad-hoc / Research-based
- Not mentioned

Documentation excerpt:
\"\"\"
{corpus[:1200]}
\"\"\"
"""



res_release = pipe(
    prompt_release,
    max_new_tokens=50,
    temperature=0.0,
    do_sample=False
)

print(res_release[0]["generated_text"])

prompt_branching = f"""
You are analyzing the development workflow of an open-source project
from a Software Engineering process perspective.

Task:
Identify the BRANCHING MODEL used by the project based on how development,
integration, and contributions are organized.

Guidelines:
- Consider whether development is centralized or spread across long-lived branches.
- Look for evidence of a main or trunk branch receiving frequent integrations.
- If the branching strategy is not clearly described, state that explicitly.

Answer ONLY with one of the following options:
- GitHub Flow
- Gitflow
- Trunk-based development
- Not explicitly defined

Documentation excerpt:
\"\"\"
{corpus[:1200]}
\"\"\"
"""


res_branch = pipe(
    prompt_branching,
    max_new_tokens=40,
    temperature=0.0,
    do_sample=False
)

print(res_branch[0]["generated_text"])

prompt_justification = f"""
The open-source project JARVIS was analyzed and classified as follows:

- Release Strategy: {res_release[0]["generated_text"]}
- Branching Model: {res_branch[0]["generated_text"]}

Task:
Provide a concise, technical justification grounded in Software Engineering principles.

Requirements:
1) Explain why the identified release strategy is appropriate for the
   project's context, goals, and nature (e.g., research-oriented development).
2) Explain why the identified branching model aligns with good practices
   for collaboration, integration, and governance in this type of project.

Constraints:
- Base your reasoning on governance, development workflow, and project context.
- Do NOT quote or summarize the documentation.
- Write 5 to 6 short, objective sentences total.
"""



res_just = pipe(
    prompt_justification,
    max_new_tokens=220,
    temperature=0.25,
    do_sample=False
)

print(res_just[0]["generated_text"])